### ISSUE TITLE
Spawn of npm on Windows gives ENOENT

### ISSUE THREAD

**Issue by erikgb** [dpratt/npm-snapshot#3]
I am trying to use npm-snapshot on Windows, but it always fails with the following error:

```
> npm-snapshot "12345"

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

I am building with Node/npm version 4.2.6/2.14.12 - if relevant. I haven't tested with other versions of Node/npm, but the exact same thing is working fine on Linux....

Might be related to nodejs/node-v0.x-archive#2318

**Comment by CSchulz** [comment]
Same with 6.5.0/3.10.3

**Comment by ducin** [comment]
Had the same on 8.9.0/5.5.1. It's a windows-specific thing, [SO to the rescue](https://stackoverflow.com/a/43285131/769384). Hope we can get the new release happen
